#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("ApexMenuSample.Resource", IsApplication=true)]

namespace ApexMenuSample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			ApexMenu.Resource.Attribute.childSize = ApexMenuSample.Resource.Attribute.childSize;
			ApexMenu.Resource.Attribute.fromDegrees = ApexMenuSample.Resource.Attribute.fromDegrees;
			ApexMenu.Resource.Attribute.toDegrees = ApexMenuSample.Resource.Attribute.toDegrees;
			ApexMenu.Resource.Drawable.bg_addbutton = ApexMenuSample.Resource.Drawable.bg_addbutton;
			ApexMenu.Resource.Drawable.bg_addbutton_highlighted = ApexMenuSample.Resource.Drawable.bg_addbutton_highlighted;
			ApexMenu.Resource.Drawable.bg_addbutton_normal = ApexMenuSample.Resource.Drawable.bg_addbutton_normal;
			ApexMenu.Resource.Drawable.bg_menuitem = ApexMenuSample.Resource.Drawable.bg_menuitem;
			ApexMenu.Resource.Drawable.bg_menuitem_highlighted_and = ApexMenuSample.Resource.Drawable.bg_menuitem_highlighted_and;
			ApexMenu.Resource.Drawable.bg_menuitem_normal_and = ApexMenuSample.Resource.Drawable.bg_menuitem_normal_and;
			ApexMenu.Resource.Drawable.icon_plus = ApexMenuSample.Resource.Drawable.icon_plus;
			ApexMenu.Resource.Drawable.icon_plus_highlighted = ApexMenuSample.Resource.Drawable.icon_plus_highlighted;
			ApexMenu.Resource.Drawable.icon_plus_normal = ApexMenuSample.Resource.Drawable.icon_plus_normal;
			ApexMenu.Resource.Drawable.monoandroidsplash = ApexMenuSample.Resource.Drawable.monoandroidsplash;
			ApexMenu.Resource.Id.control_hint = ApexMenuSample.Resource.Id.control_hint;
			ApexMenu.Resource.Id.control_layout = ApexMenuSample.Resource.Id.control_layout;
			ApexMenu.Resource.Id.item_layout = ApexMenuSample.Resource.Id.item_layout;
			ApexMenu.Resource.Layout.item = ApexMenuSample.Resource.Layout.item;
			ApexMenu.Resource.Layout.menu = ApexMenuSample.Resource.Layout.menu;
			ApexMenu.Resource.Layout.monoandroidsplash = ApexMenuSample.Resource.Layout.monoandroidsplash;
			ApexMenu.Resource.String.library_name = ApexMenuSample.Resource.String.library_name;
			ApexMenu.Resource.Style.Mono_Android_Theme_Splash = ApexMenuSample.Resource.Style.Mono_Android_Theme_Splash;
			ApexMenu.Resource.Styleable.Layout = ApexMenuSample.Resource.Styleable.Layout;
			ApexMenu.Resource.Styleable.Layout_childSize = ApexMenuSample.Resource.Styleable.Layout_childSize;
			ApexMenu.Resource.Styleable.Layout_fromDegrees = ApexMenuSample.Resource.Styleable.Layout_fromDegrees;
			ApexMenu.Resource.Styleable.Layout_toDegrees = ApexMenuSample.Resource.Styleable.Layout_toDegrees;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010002
			public const int childSize = 2130771970;
			
			// aapt resource value: 0x7f010000
			public const int fromDegrees = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int toDegrees = 2130771969;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bg_addbutton = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bg_addbutton_highlighted = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bg_addbutton_normal = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bg_menuitem = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int bg_menuitem_highlighted = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int bg_menuitem_highlighted_and = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int bg_menuitem_normal = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int bg_menuitem_normal_and = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int composer_camera_and = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int composer_music_and = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int composer_place_and = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int composer_sleep_and = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int composer_thought_and = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int composer_with_and = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Icon = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int icon_plus = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int icon_plus_highlighted = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int icon_plus_normal = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int monoandroidsplash = 2130837522;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int apex_menu = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int control_hint = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int control_layout = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int item_layout = 2131099649;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int item = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int menu = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int monoandroidsplash = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] Layout = new int[]
			{
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int Layout_childSize = 2;
			
			// aapt resource value: 0
			public const int Layout_fromDegrees = 0;
			
			// aapt resource value: 1
			public const int Layout_toDegrees = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
