#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("ApexMenu.Resource", IsApplication=false)]

namespace ApexMenu
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010002
			public static int childSize = 2130771970;
			
			// aapt resource value: 0x7f010000
			public static int fromDegrees = 2130771968;
			
			// aapt resource value: 0x7f010001
			public static int toDegrees = 2130771969;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int bg_addbutton = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int bg_addbutton_highlighted = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int bg_addbutton_normal = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int bg_menuitem = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int bg_menuitem_highlighted_and = 2130837508;
			
			// aapt resource value: 0x7f020005
			public static int bg_menuitem_normal_and = 2130837509;
			
			// aapt resource value: 0x7f020006
			public static int icon_plus = 2130837510;
			
			// aapt resource value: 0x7f020007
			public static int icon_plus_highlighted = 2130837511;
			
			// aapt resource value: 0x7f020008
			public static int icon_plus_normal = 2130837512;
			
			// aapt resource value: 0x7f020009
			public static int monoandroidsplash = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public static int control_hint = 2131099650;
			
			// aapt resource value: 0x7f060001
			public static int control_layout = 2131099649;
			
			// aapt resource value: 0x7f060000
			public static int item_layout = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int item = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int menu = 2130903041;
			
			// aapt resource value: 0x7f030002
			public static int monoandroidsplash = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public static int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public static int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] Layout = new int[]
			{
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public static int Layout_childSize = 2;
			
			// aapt resource value: 0
			public static int Layout_fromDegrees = 0;
			
			// aapt resource value: 1
			public static int Layout_toDegrees = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
